[package]
name = "toons"
version = "0.8.0"
edition = "2024"
rust-version = "1.85"
description = "Python bindings for TOON (Token Oriented Object Notation)"
repository = "https://github.com/alesanfra/toons"
license = "Apache-2.0"
publish = false

[lib]
name = "toons"
crate-type = ["cdylib"]

[dependencies]
pyo3 = { version = "0.29", features = ["experimental-inspect"] }

[profile.release]
lto = true
codegen-units = 1
strip = true
